// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MojeTwinPeaks.Models;

#nullable disable

namespace MojeTwinPeaks.Migrations.Music
{
    [DbContext(typeof(MusicContext))]
    [Migration("20241128203459_MusicInitial")]
    partial class MusicInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MojeTwinPeaks.Models.Music", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YouTubeUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("MusicTable");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Artist = "Angelo Badalamenti",
                            ImagePath = "https://twinpeaksimgstorage.blob.core.windows.net/musicimages/AudreysDance.jpg ",
                            Name = "Audrey's Dance",
                            YouTubeUrl = "https://youtu.be/nITuHzF4ryk"
                        },
                        new
                        {
                            ID = 2,
                            Artist = "Angelo Badalamenti",
                            ImagePath = "https://twinpeaksimgstorage.blob.core.windows.net/musicimages/DanceOfTheDreamMan.jpg ",
                            Name = "Dance Of The Dream Man",
                            YouTubeUrl = "https://youtu.be/kBn_lQBh9JA"
                        },
                        new
                        {
                            ID = 3,
                            Artist = "Julee Cruise",
                            ImagePath = "https://twinpeaksimgstorage.blob.core.windows.net/musicimages/Falling.jpg ",
                            Name = "Falling",
                            YouTubeUrl = "https://youtu.be/KkR6Jd0Agi4"
                        },
                        new
                        {
                            ID = 4,
                            Artist = "Angelo Badalamenti",
                            ImagePath = "https://twinpeaksimgstorage.blob.core.windows.net/musicimages/FreshlySqueezed.jpg ",
                            Name = "Freshly Squeezed",
                            YouTubeUrl = "https://youtu.be/bc-Prdyp9LY "
                        },
                        new
                        {
                            ID = 5,
                            Artist = "Julee Cruise",
                            ImagePath = "https://twinpeaksimgstorage.blob.core.windows.net/musicimages/IntoTheNight.jpg ",
                            Name = "Into The Night",
                            YouTubeUrl = "https://youtu.be/euq0sKwbDTg"
                        },
                        new
                        {
                            ID = 6,
                            Artist = "Angelo Badalamenti",
                            ImagePath = "https://twinpeaksimgstorage.blob.core.windows.net/musicimages/LauraPalmersTheme.jpg ",
                            Name = "Laura Palmers Theme",
                            YouTubeUrl = "https://youtu.be/woUt7wPe8Ow"
                        },
                        new
                        {
                            ID = 7,
                            Artist = "Angelo Badalamenti",
                            ImagePath = "https://twinpeaksimgstorage.blob.core.windows.net/musicimages/LoveTheme.jpg ",
                            Name = "Love Theme",
                            YouTubeUrl = "https://youtu.be/JwHwyejd-vk"
                        },
                        new
                        {
                            ID = 8,
                            Artist = "Angelo Badalamenti",
                            ImagePath = "https://twinpeaksimgstorage.blob.core.windows.net/musicimages/TheBookhouseBoys.jpg ",
                            Name = "The Bookhouse Boys",
                            YouTubeUrl = "https://youtu.be/rQrVeoiebWs"
                        },
                        new
                        {
                            ID = 9,
                            Artist = "Julee Cruise",
                            ImagePath = "https://twinpeaksimgstorage.blob.core.windows.net/musicimages/TheNightingale.jpg ",
                            Name = "The Nightingale",
                            YouTubeUrl = "https://youtu.be/BzImHGz4R0M"
                        },
                        new
                        {
                            ID = 10,
                            Artist = "Angelo Badalamenti",
                            ImagePath = "https://twinpeaksimgstorage.blob.core.windows.net/musicimages/TwinPeaksTheme.jpg ",
                            Name = "Twin Peaks Theme",
                            YouTubeUrl = "https://youtu.be/nCn3LYqCnrk"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
